apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: tkc-1
spec:
  distribution:
    version: v1.21
  topology:
    controlPlane:
      class: guaranteed-small
      count: 1
      storageClass: kubernetes-demo-storage-policy
    workers:
      class: guaranteed-small
      count: 1
      storageClass: kubernetes-demo-storage-policy
  settings:
    storage:
      classes: ["kubernetes-demo-storage-policy"]              #Named PVC storage classes
      defaultClass: kubernetes-demo-storage-policy                     #Default PVC storage class
